title: Timothy Kimutai
logo: "WhatsApp Image 2024-11-08 at 02.23.26.jpeg"
# description:
show_downloads: True
exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: Jekyll Theme Primer
description: Primer is a Jekyll theme for GitHub Pages
